//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckinPortal.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Inclusive of 10 % service charge and prevailing government taxes).
        /// </summary>
        internal static string _Inclusive_of_10___service_charge_and_prevailing_government_taxes_ {
            get {
                return ResourceManager.GetString("(Inclusive of 10 % service charge and prevailing government taxes)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Inclusive of Charges to Tax).
        /// </summary>
        internal static string _Inclusive_of_Charges_to_Tax_ {
            get {
                return ResourceManager.GetString("(Inclusive of Charges to Tax)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADULT/CHILD.
        /// </summary>
        internal static string Adult_Child {
            get {
                return ResourceManager.GetString("Adult/Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL Membership Number.
        /// </summary>
        internal static string ALL_Membership_Number {
            get {
                return ResourceManager.GetString("ALL Membership Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard this option?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_discard_this_option_ {
            get {
                return ResourceManager.GetString("Are you sure you want to discard this option?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORISATION DETAILS.
        /// </summary>
        internal static string AUTHORISATION_DETAILS {
            get {
                return ResourceManager.GetString("AUTHORISATION DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABLE ROOM UPGRADE.
        /// </summary>
        internal static string AVAILABLE_ROOM_UPGRADE {
            get {
                return ResourceManager.GetString("AVAILABLE ROOM UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Amount.
        /// </summary>
        internal static string Balance_Amount {
            get {
                return ResourceManager.GetString("Balance Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN SELF CHECK-OUT.
        /// </summary>
        internal static string BEGIN_SELF_CHECK_OUT {
            get {
                return ResourceManager.GetString("BEGIN SELF CHECK-OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAKFAST.
        /// </summary>
        internal static string BREAKFAST {
            get {
                return ResourceManager.GetString("BREAKFAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string Card_Number {
            get {
                return ResourceManager.GetString("Card Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK-IN DATE.
        /// </summary>
        internal static string CHECK_IN_DATE {
            get {
                return ResourceManager.GetString("CHECK-IN DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK-OUT DATE.
        /// </summary>
        internal static string CHECK_OUT_DATE {
            get {
                return ResourceManager.GetString("CHECK-OUT DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmation.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMATION NUMBER.
        /// </summary>
        internal static string CONFIRMATION_NUMBER {
            get {
                return ResourceManager.GetString("CONFIRMATION NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Privacy Policy.
        /// </summary>
        internal static string Customers_Privacy_Policy {
            get {
                return ResourceManager.GetString("Customers Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date Of Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        internal static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Details.
        /// </summary>
        internal static string Document_Details {
            get {
                return ResourceManager.GetString("Document Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  Address.
        /// </summary>
        internal static string Email__Address {
            get {
                return ResourceManager.GetString("Email  Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to enroll for complimentary ALL membership..
        /// </summary>
        internal static string Enrollment_Message {
            get {
                return ResourceManager.GetString("Enrollment Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTIMATED INCIDENTAL CHARGES.
        /// </summary>
        internal static string ESTIMATED_INCIDENTAL_CHARGES {
            get {
                return ResourceManager.GetString("ESTIMATED INCIDENTAL CHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Arrival Time (Hotel).
        /// </summary>
        internal static string Expected_Arrival_Time__Hotel_ {
            get {
                return ResourceManager.GetString("Expected Arrival Time (Hotel)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Facebook and Instagram for exclusive offers and updates..
        /// </summary>
        internal static string Follow_us_on_Facebook_and_Instagram_for_exclusive_offers_and_updates_ {
            get {
                return ResourceManager.GetString("Follow us on Facebook and Instagram for exclusive offers and updates.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUEST DETAILS.
        /// </summary>
        internal static string GUEST_DETAILS {
            get {
                return ResourceManager.GetString("GUEST DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the charges stated on the Tax Invoice.(Please review your invoice now but only proceed to tick before you leave your room. Otherwise your room key will be disabled.).
        /// </summary>
        internal static string I_agree_to_the_charges_stated_on_the_Tax_Invoice__Please_review_your_invoice_now_but_only_proceed_to_tick_before_you_leave_your_room__Otherwise_your_room_key_will_be_disabled__ {
            get {
                return ResourceManager.GetString("I agree to the charges stated on the Tax Invoice.(Please review your invoice now " +
                        "but only proceed to tick before you leave your room. Otherwise your room key wil" +
                        "l be disabled.)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the charges stated on the Tax Invoice.(Please review your invoice now but only proceed to tick before you leave your room. Otherwise your room key will be disabled.).
        /// </summary>
        internal static string I_agree_to_the_charges_stated_on_the_Tax_Invoice_Please_review_your_invoice_now_but_only_proceed_to_tick_before_you_leave_your_room__Otherwise_your_room_key_will_be_disabled_ {
            get {
                return ResourceManager.GetString("I agree to the charges stated on the Tax Invoice.Please review your invoice now b" +
                        "ut only proceed to tick before you leave your room. Otherwise your room key will" +
                        " be disabled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to receive marketing information from Mercure Amsterdam City related to our services, including dedicated offers and promotions, on the provided email address or by sms to a given mobile phone number..
        /// </summary>
        internal static string I_would_like_to_receive_marketing_information_from_Novotel_Paris_Vaugirard__related_to_our_services__including_dedicated_offers_and_promotions__on_the_provided_email_address_or_by_sms_to_a_given_mobile_phone_number_ {
            get {
                return ResourceManager.GetString("I would like to receive marketing information from Novotel Paris Vaugirard* relat" +
                        "ed to our services, including dedicated offers and promotions, on the provided e" +
                        "mail address or by sms to a given mobile phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        internal static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Included.
        /// </summary>
        internal static string Not_Included {
            get {
                return ResourceManager.GetString("Not Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercure Amsterdam City Hotel wishes you a pleasant day ahead!.
        /// </summary>
        internal static string Novotel_Paris_Vaugirard_wishes_you_a_pleasant_day_ahead_ {
            get {
                return ResourceManager.GetString("Novotel Paris Vaugirard wishes you a pleasant day ahead!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No / CNI.
        /// </summary>
        internal static string Passport_Number {
            get {
                return ResourceManager.GetString("Passport Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment process failed.
        /// </summary>
        internal static string Payment_process_failed {
            get {
                return ResourceManager.GetString("Payment process failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per room per night.
        /// </summary>
        internal static string per_room_per_night {
            get {
                return ResourceManager.GetString("per room per night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Personal_Information {
            get {
                return ResourceManager.GetString("Personal Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Birth.
        /// </summary>
        internal static string Place_Of_Birth {
            get {
                return ResourceManager.GetString("Place Of Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Issue.
        /// </summary>
        internal static string Place_Of_Issue {
            get {
                return ResourceManager.GetString("Place Of Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms and conditions.
        /// </summary>
        internal static string Please_accept_the_terms_and_conditions {
            get {
                return ResourceManager.GetString("Please accept the terms and conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed, that by booking your stay at our hotel you also accept hotel’s regulations that might apply to your stay depending on a hotel you choose. For any further information with this regards, please contact with a reception desk of hotel you are staying with..
        /// </summary>
        internal static string Please_be_informed__that_by_completing_this_pre_arrival_registration_you_also_accept_hotels_regulations_that_might_apply_to_your_stay_depending_on_a_hotel_you_choose__For_any_further_information_with_this_regard__please_contact_with_a_reception_desk_of_hotel_your_are_staying_with_ {
            get {
                return ResourceManager.GetString(@"Please be informed, that by completing this pre-arrival registration you also accept hotels regulations that might apply to your stay depending on a hotel you choose. For any further information with this regard, please contact with a reception desk of hotel your are staying with.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed, that by booking your stay at our hotel you also accept our.
        /// </summary>
        internal static string Please_be_informed__that_by_completing_this_pre_arrival_registration_you_also_accept_our {
            get {
                return ResourceManager.GetString("Please be informed, that by completing this pre-arrival registration you also acc" +
                        "ept our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact front desk for assistance..
        /// </summary>
        internal static string Please_contact_front_desk_for_assistance_ {
            get {
                return ResourceManager.GetString("Please contact front desk for assistance.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address.
        /// </summary>
        internal static string Please_enter_email_address {
            get {
                return ResourceManager.GetString("Please enter email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select card to proceed.
        /// </summary>
        internal static string Please_select_card_to_proceed {
            get {
                return ResourceManager.GetString("Please select card to proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your authorisation details.
        /// </summary>
        internal static string Please_verify_your_authorisation_details {
            get {
                return ResourceManager.GetString("Please verify your authorisation details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string Postal_code {
            get {
                return ResourceManager.GetString("Postal code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for Specials is confirmed instantly and your card will be charged in the next page..
        /// </summary>
        internal static string Request_for_Specials_is_confirmed_instantly_and_your_card_will_be_charged_in_the_next_page_ {
            get {
                return ResourceManager.GetString("Request for Specials is confirmed instantly and your card will be charged in the " +
                        "next page.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM TYPE.
        /// </summary>
        internal static string ROOM_TYPE {
            get {
                return ResourceManager.GetString("ROOM TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign above.
        /// </summary>
        internal static string Sign_above {
            get {
                return ResourceManager.GetString("Sign above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to our mailing list or follow us on Facebook and Instagram for exclusive offers and updates..
        /// </summary>
        internal static string Subscribe_to_our_mailing_list_or_follow_us_on_Facebook_and_Instagram_for_exclusive_offers_and_updates_ {
            get {
                return ResourceManager.GetString("Subscribe to our mailing list or follow us on Facebook and Instagram for exclusiv" +
                        "e offers and updates.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Invoice.
        /// </summary>
        internal static string Tax_Invoice {
            get {
                return ResourceManager.GetString("Tax Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string Thank_You {
            get {
                return ResourceManager.GetString("Thank You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking the time to complete the PRE-ARRIVAL REGISTRATION. Please find the attached QR code and confirmation number, and save it for presentation at the hotel to collect your room key..
        /// </summary>
        internal static string Thank_you_for_taking_the_time_to_complete_the_PRE_ARRIVAL_REGISTRATION__Please_find_the_attached_QR_code_and_confirmation_number__and_save_it_for_presentation_at_the_hotel_to_collect_your_room_key_ {
            get {
                return ResourceManager.GetString("Thank you for taking the time to complete the PRE-ARRIVAL REGISTRATION. Please fi" +
                        "nd the attached QR code and confirmation number, and save it for presentation at" +
                        " the hotel to collect your room key.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you once again for choosing Mercure Amsterdam City. We look forward to welcome you back soon..
        /// </summary>
        internal static string Thank_you_once_again_for_choosing_Novotel_Paris_Vaugirard__We_look_forward_to_welcome_you_back_soon_ {
            get {
                return ResourceManager.GetString("Thank you once again for choosing Novotel Paris Vaugirard. We look forward to wel" +
                        "come you back soon.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Room Key will be disabled..
        /// </summary>
        internal static string The_Room_Key_will_be_disabled_ {
            get {
                return ResourceManager.GetString("The Room Key will be disabled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected upgrade option is subject to availability at the time of reservation. Our team will be in touch shortly to confirm..
        /// </summary>
        internal static string The_selected_upgrade_option_is_subject_to_availability_at_the_time_of_reservation__Our_team_will_be_in_touch_shortly_to_confirm_ {
            get {
                return ResourceManager.GetString("The selected upgrade option is subject to availability at the time of reservation" +
                        ". Our team will be in touch shortly to confirm.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive a copy of your invoice via email.
        /// </summary>
        internal static string To_receive_a_copy_of_your_invoice_via_email {
            get {
                return ResourceManager.GetString("To receive a copy of your invoice via email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive copy of your invoice to another email.
        /// </summary>
        internal static string To_receive_copy_of_your_invoice_to_another_email {
            get {
                return ResourceManager.GetString("To receive copy of your invoice to another email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL ROOM CHARGES.
        /// </summary>
        internal static string TOTAL_ROOM_CHARGES {
            get {
                return ResourceManager.GetString("TOTAL ROOM CHARGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process payment.
        /// </summary>
        internal static string Unable_to_process_payment {
            get {
                return ResourceManager.GetString("Unable to process payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent your invoice to the email provided. You will receive it within 15 minutes..
        /// </summary>
        internal static string We_have_sent_your_invoice_to_the_email_provided__You_will_receive_it_within_15_minutes_ {
            get {
                return ResourceManager.GetString("We have sent your invoice to the email provided. You will receive it within 15 mi" +
                        "nutes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have successfully processed your check-out request..
        /// </summary>
        internal static string We_have_successfully_processed_your_check_out_request_ {
            get {
                return ResourceManager.GetString("We have successfully processed your check-out request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which includes all relevant information regarding processing of your personal data by our hotel..
        /// </summary>
        internal static string which_includes_all_relevant_information_regarding_processing_of_your_personal_data_by_our_hotel_ {
            get {
                return ResourceManager.GetString("which includes all relevant information regarding processing of your personal dat" +
                        "a by our hotel.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use the existing card?.
        /// </summary>
        internal static string Would_you_like_to_use_the_existing_card_ {
            get {
                return ResourceManager.GetString("Would you like to use the existing card?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully checked out..
        /// </summary>
        internal static string You_have_successfully_checked_out_ {
            get {
                return ResourceManager.GetString("You have successfully checked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment was successful.
        /// </summary>
        internal static string Your_payment_was_successful {
            get {
                return ResourceManager.GetString("Your payment was successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Room Key will now be disabled..
        /// </summary>
        internal static string Your_Room_Key_will_now_be_disabled_ {
            get {
                return ResourceManager.GetString("Your Room Key will now be disabled.", resourceCulture);
            }
        }
    }
}
